#!/bin/sh -e
patch -Np1 -i ../kbd-2.7.1-backspace-1.patch || true
[ -f configure ] && sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure || true
./configure --prefix=/usr --disable-vlock
make
make DESTDIR="$1" install
