#!/bin/sh -e
./configure --prefix=/usr --sysconfdir=/etc \
    --disable-setuid --enable-cache-owner=bin \
    --with-browser=/usr/bin/lynx --with-vgrind=/usr/bin/vgrind \
    --with-grap=/usr/bin/grap
make
make DESTDIR="$1" install
