#!/bin/sh -e
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var \
    --runstatedir=/run --enable-user-session --disable-static \
    --disable-doxygen-docs --disable-xml-docs
make
make DESTDIR="$1" install
