#!/bin/sh -e
patch -Np1 -i bzip2-1.0.8-install_docs-1.patch || true
sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
sed -i 's@(PREFIX)/man@(PREFIX)/share/man@g' Makefile
make -f Makefile-libbz2_so
make clean
make
make PREFIX="$1/usr" install
cp -av libbz2.so.* "$1/usr/lib/"
ln -sv libbz2.so.1.0.8 "$1/usr/lib/libbz2.so"
cp -v bzip2-shared "$1/usr/bin/bzip2"
for i in bzcat bunzip2; do
    ln -sfv bzip2 "$1/usr/bin/$i"
done
rm -fv "$1/usr/lib/libbz2.a"
