#!/bin/sh -e
./configure --bindir=/usr/bin --libdir=/usr/lib --runstatedir=/run --sbindir=/usr/sbin \
    --disable-chfn-chsh --disable-login --disable-nologin --disable-su \
    --disable-setpriv --disable-runuser --disable-pylibmount --disable-static \
    --disable-liblastlog2 --without-python \
    ADJTIME_PATH=/var/lib/hwclock/adjtime
make
make DESTDIR="$1" install
