#!/bin/sh -e
pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps "$PWD" || \
    python3 -m flit_core.wheel || true
pip3 install --no-index --no-user --find-links dist --no-cache-dir \
    --root="$1" --prefix=/usr flit_core || true
