#!/bin/sh -e
mkdir -v build && cd build
../configure --prefix=/usr \
    --sysconfdir=/etc \
    --enable-ld=default \
    --enable-plugins \
    --enable-shared \
    --disable-werror \
    --enable-64-bit-bfd \
    --enable-new-dtags \
    --with-system-zlib \
    --enable-default-hash-style=gnu
make tooldir=/usr
make tooldir=/usr DESTDIR="$1" install
rm -fv "$1/usr/lib/lib"{bfd,ctf,ctf-nobfd,opcodes,sframe}.a
