#!/bin/sh -e
./configure --prefix=/usr --disable-debuginfod --enable-libdebuginfod=dummy
make
make -C libelf DESTDIR="$1" install
install -vm644 config/libelf.pc "$1/usr/lib/pkgconfig/"
rm -v "$1/usr/lib/libelf.a" 2>/dev/null || true
