#!/bin/sh -e
# Stub out gtk-doc macros that aren't available in LFS
mkdir -p m4
cat > m4/gtk-doc.m4 <<'GTKM4'
AC_DEFUN([GTK_DOC_CHECK],[
  AM_CONDITIONAL([ENABLE_GTK_DOC],[false])
  AM_CONDITIONAL([GTK_DOC_USE_LIBTOOL],[false])
  AM_CONDITIONAL([GTK_DOC_USE_REBASE],[false])
  AM_CONDITIONAL([GTK_DOC_BUILD_HTML],[false])
  AM_CONDITIONAL([GTK_DOC_BUILD_PDF],[false])
  AC_SUBST([GTKDOC_CHECK])
  AC_SUBST([GTKDOC_CHECK_PATH])
  AC_SUBST([GTKDOC_REBASE])
  AC_SUBST([GTKDOC_MKPDF])
])
GTKM4
install -Dm644 /dev/null libkmod/docs/gtk-doc.make 2>/dev/null || true
sed -i '/^GTK_DOC_CHECK/d' configure.ac
autoreconf -fi
./configure --prefix=/usr --sysconfdir=/etc \
    --with-openssl --with-xz --with-zstd --with-zlib \
    --disable-manpages
make ACLOCAL=: AUTOCONF=: AUTOMAKE=: AUTOHEADER=: MAKEINFO=:
make ACLOCAL=: AUTOCONF=: AUTOMAKE=: AUTOHEADER=: MAKEINFO=: DESTDIR="$1" install
for t in depmod insmod modinfo modprobe rmmod; do
    ln -sfv ../bin/kmod "$1/usr/sbin/$t"
done
ln -sfv kmod "$1/usr/bin/lsmod"
