#!/bin/sh -e
sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;
sed -e 's:#ENCRYPT_METHOD DES:ENCRYPT_METHOD YESCRYPT:' \
    -e 's:/var/spool/mail:/var/mail:' \
    -e '/PATH=/{s@/sbin:@@;s@/bin:@@}' \
    -i etc/login.defs
touch "$1/usr/bin/passwd"
./configure --sysconfdir=/etc --disable-static --with-{b,yes}crypt \
    --without-libbsd --with-group-name-max-length=32
make
make exec_prefix=/usr DESTDIR="$1" install
make -C man DESTDIR="$1" install-man
